import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Player from "@/components/Player";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, "h-full flex flex-col")}>
        <Header className="flex-shrink-0 flex-grow-0" />
        <main className="flex-1 overflow-y-auto">{children}</main>
        <Player className="flex-shrink-0 flex-grow-0" />
      </body>
    </html>
  );
}
